apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-controller
{{ include "imagePullSecrets" . }}
{{- if .Values.bootstrap.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-controller-bootstrap
{{ include "imagePullSecrets" . }}
{{- end }}
