url: https://github.com/harrisonwaffel/fleet.git
chartRepoBranch: auth-reg
subdirectory: charts/fleet
workingDir: fleet
version: 109.0.0
additionalCharts:
  - workingDir: fleet-crd
    upstreamOptions:
      url: https://github.com/harrisonwaffel/fleet.git
      chartRepoBranch: auth-reg
      subdirectory: charts/fleet-crd
  - workingDir: fleet-agent
    upstreamOptions:
      url: https://github.com/harrisonwaffel/fleet.git
      chartRepoBranch: auth-reg
      subdirectory: charts/fleet-agent