apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher-webhook
{{- include "imagePullSecrets" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher-webhook-sudo
  annotations:
    cattle.io/description: "SA which can be impersonated to bypass rancher-webhook validation"