auto: true
url: https://github.com/harrisonwaffel/eks-operator.git
chartRepoBranch: image-pull-secret-support
subdirectory: charts/eks-operator
workingDir: rancher-eks-operator
additionalCharts:
  - workingDir: rancher-eks-operator-crd
    upstreamOptions:
      url: https://github.com/harrisonwaffel/eks-operator.git
      chartRepoBranch: image-pull-secret-support
      subdirectory: charts/eks-operator-crd
