apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: system-upgrade-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: system-upgrade-controller
    spec:
      affinity: {}
      containers:
        - name: system-upgrade-controller
          image: {{ template "system_default_registry" . }}{{ .Values.systemUpgradeController.image.repository }}:{{ .Values.systemUpgradeController.image.tag }}
          imagePullPolicy: Always
