{{- if .Values.global.cattle.systemDefaultRegistryPullInfo }}
apiVersion: v1
kind: Secret
metadata:
  name: myregistry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
