annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/kube-version: '>= 1.25.0-0 < 1.37.0-0'
  catalog.cattle.io/managed: "true"
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/release-name: basic-test
apiVersion: v1
appVersion: v0.19.1
description: testing
home: https://github.com/rancher/system-upgrade-controller
kubeVersion: '>= 1.25.0-0'
name: basic-test
version: 110.0.0
